# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [2]:
# CODE HERE

import numpy as np
import torch

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [3]:
# CODE HERE
one = np.random.seed(42)
two =torch.manual_seed(42)

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [4]:
# CODE HERE
arr = np.random.randint(0,5,size=6)

In [5]:
# DON'T WRITE HERE

### 4. Create a tensor "x" from the array above

In [6]:

x = torch.from_numpy(arr).to(torch.int32)

In [ ]:
# DON'T WRITE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [7]:
# CODE HERE
x = x.to(torch.int64)

In [ ]:
# DON'T WRITE HERE

torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [8]:
# CODE HERE
x_reshaped = x.reshape(3, 2)



In [ ]:
# DON'T WRITE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [12]:
# CODE HERE
right_column = x[1]

In [ ]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [14]:
# CODE HERE
x_squared = x ** 2



In [ ]:
# DON'T WRITE HERE

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [16]:
# CODE
y = torch.randint(0, 5, (2, 3))



In [ ]:
# DON'T WRITE HERE

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Find the matrix product of x and y

In [23]:
result = torch.mm(x_reshaped, y)
result = torch.mm(x_reshaped, y)
print("x reshaped:\n", x_reshaped)
print("y:\n", y)
print("Matrix multiplication result:\n",result)

x reshaped:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
y:
 tensor([[2, 2, 1],
        [4, 1, 0]])
Matrix multiplication result:
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


In [ ]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Great job!